puts 'We are using puts'
puts 'What does puts do, well it prints out to the screen'
puts 'What are other forms'
puts 'We have p, print, and puts'
puts 'They are all a little different but I always forget how'
puts 'Maybe I should find out'
p 'This is using p'
print 'This is using print'
puts 'This is using puts'
